### ISSUE TITLE
Adding new component containing *.spec.ts crashes the project tests

### ISSUE THREAD

**Issue by simonbor** [OpenBudget/budgetkey-app-search#75] opened 2017-09-25 18:57 UTC
Adding an empty *.spec.ts file to the .\app folder fail the application tests.
Please help

Thanks,

**Comment by kravets-levko** [comment] 2017-09-26 11:14
Hi @simonbor! I spent some on your issue and cannot reproduce it. Can you provide more info about what are you doing, your system, etc? Also output from `npm test` will be really useful. Thanks!

**Comment by simonbor** [comment] 2017-09-27 07:52
Hi,
The reproduce steps:
1. clone the app and run "npm i"
2. run npm test and check out tests success
3. create new folder "spec_test" in app folder
4. create empty new "spec_test.component.spec.ts" in app/spec_test folder
5. run npm test and see that tests fail

Expected: add *.spec.ts empty files to any component and run test success
Actual: after add *.spec.ts empty files the tests fail

the output - 
![image](https://user-images.githubusercontent.com/8211293/30901671-701d2cca-a371-11e7-87df-4cc4bdfdeea7.png)

**Comment by kravets-levko** [comment] 2017-09-27 08:08
Hi @simonbor!

Thank you for that info - it was useful. As you can see, tests are actually passing - look at the most bottom line of output. That errors are from TypeScript linter, and it's strange that they are displayed only when we have more than one `.spec.ts` file. Anyway, you can create your tests, they will run, meanwhile I'll try to understand what's wrong with linter.

**Comment by kravets-levko** [comment] 2017-09-27 09:00
@simonbor,
I prepared PR that should fix your issue, - can you review it please? PR https://github.com/OpenBudget/budgetkey-app-search/pull/76

**Comment by kravets-levko** [comment] 2017-09-27 12:19
@simonbor PR is merged, please update your codebase

**Closed** 2017-10-23 05:24 UTC
Labels: help wanted
